---
title: قم بتثبيت واستخدام Visual Studio مع Unity
hero_image: images/banner.png
description: قم بتثبيت واستخدام Visual Studio مع Unity
version: 4
listed: false
copyedit: false
last_tested: "2021-11-19"
steps:
  - title: Unity وVisual Studio
